# Generated by Django 5.1.7 on 2025-03-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('review', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
